apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: test-vol
      mountPath: "/etc/non-sensitive-data"
      readOnly: true
    volumes:
    - name: test-vol
      configMap:
        name: nginx-configmap
        - key: file-1.txt
          path: file-a.txt
        - key: file-2.txt
          path: file-b.txt
